on:
  push:
    branches: [main, master]
  pull_request:
jobs:
  pytest:
    runs-on: ubuntu-latest
    name: pytest (Python ${{ matrix.python-version }})
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python-version }}"
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install .
      - name: Run tests
        run: pytest
  pycodestyle:
    runs-on: ubuntu-latest
    name: pycodestyle
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install pycodestyle
          pip install .
      - name: Run tests
        run: pycodestyle --max-line-length=120
  pylint:
    runs-on: ubuntu-latest
    name: pylint
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install .
      - name: Run tests
        run: pylint fineslice test_fineslice --rcfile=.pylintrc
